package gitlet;

import java.util.*;
import java.text.SimpleDateFormat;
import java.util.Date;

import static gitlet.Utils.*;

public class Commit implements Save {
    private String message;
    private String timestamp;
    private String parentHashID; // Generated by a commit self-hashing.
    private Commit parent;
    private Set<Map<String, String>> fileHashes;
    private String hashID;
    private String shortenedHashID;
    private String branchMom;

    public Commit (String message, String parentID, Set<Map<String, String>> fileHashes, String branchMom, Commit parent) {
        String pattern = "EEE MMM dd HH:mm:ss yyyy Z";
        SimpleDateFormat metaTime = new SimpleDateFormat(pattern);
        this.message = message;
        this.parentHashID = parentID;
        this.parent = parent;
        this.fileHashes = fileHashes;
        this.hashID = this.generateHashID();
        this.timestamp = metaTime.format(new Date());
        this.branchMom = branchMom;
    }

    public Commit() {
        this.message = "initial commit";
        String pattern = "EEE MMM dd HH:mm:ss yyyy Z";
        SimpleDateFormat metaTime = new SimpleDateFormat(pattern);
        this.timestamp = metaTime.format(new Date(0));
        this.parentHashID = null;
        this.parent = null;
        this.fileHashes = new HashSet<>();
        this.hashID = sha1(serialize(this), this.message);
        this.shortenedHashID = this.hashID.substring(0, 8);
        this.branchMom = "main";
    }

    private String generateHashID() {
//        return sha1(this.message, parentHashID, this.fileHashes);
        String hash = sha1(serialize(this), this.message);
        this.shortenedHashID = hash.substring(0, 8);
        return hash;
    }

    public Set<Map<String, String>> getFileHashes() {
        return this.fileHashes;
    }

    public String getMessage() {
        return this.message;
    }

    public String getTimestamp() {
        return this.timestamp;
    }

    public Commit getParent() {
        return this.parent;
    }

    public String getHashID() {
        return this.hashID;
    }

    public String getShortenedHashID() {
        return this.shortenedHashID;
    }

    public String getParentID() {
        return this.parentHashID;
    }

    public String getBranchMom() {
        return this.branchMom;
    }

    @Override
    public String toString() {
        String res = "";

        res += "Parent Hash ID " +  this.parentHashID + "\n";
        res += "Time Stamp: " + this.timestamp + "\n";
        res += "Commit Message: " + this.message + "\n";
        res += "Dual Keys: ";
        for (Map<String, String> fileHash : fileHashes) {
            Map.Entry<String, String> entry = fileHash.entrySet().iterator().next();
            String k1 = entry.getKey();
            String k2 = entry.getValue();
            res += "{ key1: " + k1 + "," + "key2: " + k2 + "}" + "\n";
        }
        return res;
    }

}
